apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailman.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mailman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mailman.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostname: {{ .Values.mailman.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mailman.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MM_HOSTNAME
              value: {{ .Values.mailman.hostname }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.mailman.dbUrl.existingSecretName . }}
                  key: {{ tpl .Values.mailman.dbUrl.existingSecretKey . }}
            - name: MTA
              value: {{ .Values.mailman.mta }}
            - name: SMTP_HOST
              value: {{ .Values.mailman.smtpHost }}
            - name: SMTP_PORT
              value: "{{ .Values.mailman.smtpPort }}"
            - name: MAILARCHIVE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.mailman.mailarchiver.apiKey.existingSecretName . }}
                  key: {{ tpl .Values.mailman.mailarchiver.apiKey.existingSecretKey . }}
            - name: MAILARCHIVE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.mailman.mailarchiver.baseUrl.existingSecretName . }}
                  key: {{ tpl .Values.mailman.mailarchiver.baseUrl.existingSecretKey . }}
            - name: MAILARCHIVE_DESTINATION
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.mailman.mailarchiver.destination.existingSecretName . }}
                  key: {{ tpl .Values.mailman.mailarchiver.destination.existingSecretKey . }}
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
            - name: lmtp
              containerPort: {{ .Values.service.lmtpPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /opt/mailman/var
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "mailman.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
