{{- if .Values.mailarchiveSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mailarchiveSecret.name }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}

type: Opaque
data:
  apiKey: {{ .Values.mailarchiveSecret.apiKey | b64enc }}
  baseUrl: {{ .Values.mailarchiveSecret.baseUrl | b64enc }}
  destination: {{ .Values.mailarchiveSecret.destination | b64enc }}
{{- end }}
